from .cache_map_nodes import NODE_CLASS_MAPPINGS as CACHE_MAP_NODES
from .cache_map_nodes import NODE_DISPLAY_NAME_MAPPINGS as CACHE_MAP_NAMES
from .extract_metadata_node import NODE_CLASS_MAPPINGS as METADATA_NODES
from .extract_metadata_node import NODE_DISPLAY_NAME_MAPPINGS as METADATA_NAMES

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(CACHE_MAP_NODES)
NODE_CLASS_MAPPINGS.update(METADATA_NODES)

NODE_DISPLAY_NAME_MAPPINGS.update(CACHE_MAP_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(METADATA_NAMES)

WEB_DIRECTORY = "./js"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
